import Planner from "./planner";

export default function Home() {
  return (
    <main className="mx-auto w-full max-w-3xl px-4 py-10 sm:py-14">
      <header className="mb-8">
        <p className="text-sm font-medium tracking-wide text-leaf uppercase">Frost Window</p>
        <h1 className="mt-1 text-3xl font-semibold tracking-tight sm:text-4xl">Know when it&apos;s safe to plant. Then go outside.</h1>
        <p className="mt-3 max-w-2xl text-muted">
          Tell it where you live and what you want to grow. It reads thirty years of your local weather to find your
          frost dates, and an open-weight model running on your own machine turns that into a dated plan and a reason
          to get outdoors this weekend.
        </p>
      </header>
      <Planner />
      <footer className="mt-14 border-t border-line pt-5 text-xs leading-relaxed text-muted">
        Weather data by{" "}
        <a className="underline" href="https://open-meteo.com/">
          Open-Meteo.com
        </a>{" "}
        (CC BY 4.0). Dates are computed from the data, never generated by the model. Planting offsets follow common
        extension-service guidance; check local advice for your variety.
      </footer>
    </main>
  );
}
